idf_component_register(
    SRCS 
        "port/i_main.c"
        "port/i_system.c"
        "port/i_video.c"
        "port/i_net.c"
        "port/i_sound.c"
        "../../src/games/DOOM/linuxdoom-1.10/am_map.c"
        "../../src/games/DOOM/linuxdoom-1.10/d_items.c"
        "../../src/games/DOOM/linuxdoom-1.10/d_main.c"
        "../../src/games/DOOM/linuxdoom-1.10/d_net.c"
        "../../src/games/DOOM/linuxdoom-1.10/doomdef.c"
        "../../src/games/DOOM/linuxdoom-1.10/doomstat.c"
        "../../src/games/DOOM/linuxdoom-1.10/dstrings.c"
        "../../src/games/DOOM/linuxdoom-1.10/f_finale.c"
        "../../src/games/DOOM/linuxdoom-1.10/f_wipe.c"
        "../../src/games/DOOM/linuxdoom-1.10/g_game.c"
        "../../src/games/DOOM/linuxdoom-1.10/hu_lib.c"
        "../../src/games/DOOM/linuxdoom-1.10/hu_stuff.c"
        "../../src/games/DOOM/linuxdoom-1.10/info.c"
        "../../src/games/DOOM/linuxdoom-1.10/m_argv.c"
        "../../src/games/DOOM/linuxdoom-1.10/m_bbox.c"
        "../../src/games/DOOM/linuxdoom-1.10/m_cheat.c"
        "../../src/games/DOOM/linuxdoom-1.10/m_fixed.c"
        "../../src/games/DOOM/linuxdoom-1.10/m_menu.c"
        "../../src/games/DOOM/linuxdoom-1.10/m_misc.c"
        "../../src/games/DOOM/linuxdoom-1.10/m_random.c"
        "../../src/games/DOOM/linuxdoom-1.10/m_swap.c"
        "../../src/games/DOOM/linuxdoom-1.10/p_ceilng.c"
        "../../src/games/DOOM/linuxdoom-1.10/p_doors.c"
        "../../src/games/DOOM/linuxdoom-1.10/p_enemy.c"
        "../../src/games/DOOM/linuxdoom-1.10/p_floor.c"
        "../../src/games/DOOM/linuxdoom-1.10/p_inter.c"
        "../../src/games/DOOM/linuxdoom-1.10/p_lights.c"
        "../../src/games/DOOM/linuxdoom-1.10/p_map.c"
        "../../src/games/DOOM/linuxdoom-1.10/p_maputl.c"
        "../../src/games/DOOM/linuxdoom-1.10/p_mobj.c"
        "../../src/games/DOOM/linuxdoom-1.10/p_plats.c"
        "../../src/games/DOOM/linuxdoom-1.10/p_pspr.c"
        "../../src/games/DOOM/linuxdoom-1.10/p_saveg.c"
        "../../src/games/DOOM/linuxdoom-1.10/p_setup.c"
        "../../src/games/DOOM/linuxdoom-1.10/p_sight.c"
        "../../src/games/DOOM/linuxdoom-1.10/p_spec.c"
        "../../src/games/DOOM/linuxdoom-1.10/p_switch.c"
        "../../src/games/DOOM/linuxdoom-1.10/p_telept.c"
        "../../src/games/DOOM/linuxdoom-1.10/p_tick.c"
        "../../src/games/DOOM/linuxdoom-1.10/p_user.c"
        "../../src/games/DOOM/linuxdoom-1.10/r_bsp.c"
        "../../src/games/DOOM/linuxdoom-1.10/r_data.c"
        "../../src/games/DOOM/linuxdoom-1.10/r_draw.c"
        "../../src/games/DOOM/linuxdoom-1.10/r_main.c"
        "../../src/games/DOOM/linuxdoom-1.10/r_plane.c"
        "../../src/games/DOOM/linuxdoom-1.10/r_segs.c"
        "../../src/games/DOOM/linuxdoom-1.10/r_sky.c"
        "../../src/games/DOOM/linuxdoom-1.10/r_things.c"
        "../../src/games/DOOM/linuxdoom-1.10/s_sound.c"
        "../../src/games/DOOM/linuxdoom-1.10/sounds.c"
        "../../src/games/DOOM/linuxdoom-1.10/st_lib.c"
        "../../src/games/DOOM/linuxdoom-1.10/st_stuff.c"
        "../../src/games/DOOM/linuxdoom-1.10/tables.c"
        "../../src/games/DOOM/linuxdoom-1.10/v_video.c"
        "../../src/games/DOOM/linuxdoom-1.10/w_wad.c"
        "../../src/games/DOOM/linuxdoom-1.10/wi_stuff.c"
        "../../src/games/DOOM/linuxdoom-1.10/z_zone.c"
    INCLUDE_DIRS 
        "include"
        "../../src/games/DOOM/linuxdoom-1.10"
    REQUIRES 
        meantendo_core
        meantendo_display
        meantendo_input
        fatfs
        spiffs
        nvs_flash
)

# Define NORMALUNIX to make DOOM happy, but we'll override specifcs
target_compile_definitions(${COMPONENT_LIB} PRIVATE 
    -DNORMALUNIX 
    -DLINUX 
    -DSCREENWIDTH=320 
    -DSCREENHEIGHT=200
)
